/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(1)                                                        */
/* BINDTOOL_HEADER_FILE(burst_power_detector.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f016d494506f88bbee03ef0215c08dae)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/sandia_utils/burst_power_detector.h>
// pydoc.h is automatically generated in the build directory
#include <burst_power_detector_pydoc.h>

void bind_burst_power_detector(py::module& m)
{

    using burst_power_detector = ::gr::sandia_utils::burst_power_detector;


    py::class_<burst_power_detector,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<burst_power_detector>>(
        m, "burst_power_detector", D(burst_power_detector))

        .def(py::init(&burst_power_detector::make),
             py::arg("naverage"),
             py::arg("nguard"),
             py::arg("threshold"),
             py::arg("holdoff"),
             D(burst_power_detector, make))


        ;
}
