/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(1)                                                        */
/* BINDTOOL_HEADER_FILE(compute_stats.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(43c6ac1aa7e269f14f3663362650eadf)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/sandia_utils/compute_stats.h>
// pydoc.h is automatically generated in the build directory
#include <compute_stats_pydoc.h>

void bind_compute_stats(py::module& m)
{

    using compute_stats = ::gr::sandia_utils::compute_stats;


    py::class_<compute_stats, gr::block, gr::basic_block, std::shared_ptr<compute_stats>>(
        m, "compute_stats", D(compute_stats))

        .def(py::init(&compute_stats::make), D(compute_stats, make))


        ;
}
