/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(1)                                                        */
/* BINDTOOL_HEADER_FILE(message_vector_file_sink.h) */
/* BINDTOOL_HEADER_FILE_HASH(24d5edc96697011c189bebf12ed394e4)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/sandia_utils/message_vector_file_sink.h>
// pydoc.h is automatically generated in the build directory
#include <message_vector_file_sink_pydoc.h>

void bind_message_vector_file_sink(py::module& m)
{

    using message_vector_file_sink = ::gr::sandia_utils::message_vector_file_sink;


    py::class_<message_vector_file_sink,
               gr::block,
               gr::basic_block,
               std::shared_ptr<message_vector_file_sink>>(
        m, "message_vector_file_sink", D(message_vector_file_sink))

        .def(py::init(&message_vector_file_sink::make),
             py::arg("filename"),
             py::arg("append") = false,
             D(message_vector_file_sink, make))


        ;
}
