/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(file_source.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(56cac55772cf4c09bfdc68914ead43ef)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <sandia_utils/file_source.h>
// pydoc.h is automatically generated in the build directory
#include <file_source_pydoc.h>

void bind_file_source(py::module& m)
{

    using file_source    = gr::sandia_utils::file_source;


    py::class_<file_source,
        gr::sync_block,
        gr::block,
        gr::basic_block,
        std::shared_ptr<file_source>>(m, "file_source", D(file_source))

        .def(py::init(&file_source::make),
           py::arg("itemsize"),
           py::arg("filename"),
           py::arg("type"),
           py::arg("repeat") =  false,
           py::arg("force_new") =  false,
           D(file_source,make)
        )
        



        ;




}








