/*
 * Copyright 2018, 2019, 2020 National Technology & Engineering Solutions of Sandia, LLC
 * (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S. Government
 * retains certain rights in this software.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(invert_tune.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(03e1bfbf96f4f6d0ae8b94bb84a3cee2)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <sandia_utils/invert_tune.h>
// pydoc.h is automatically generated in the build directory
#include <invert_tune_pydoc.h>

void bind_invert_tune(py::module& m)
{

    using invert_tune    = gr::sandia_utils::invert_tune;


    py::class_<invert_tune,
        gr::block,
        gr::basic_block,
        std::shared_ptr<invert_tune>>(m, "invert_tune", D(invert_tune))

        .def(py::init(&invert_tune::make),
           D(invert_tune,make)
        )




        ;




}








